spring:
  application:
    name: ProjectApi
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  batch:
    jdbc:
      initialize-schema: always   # crée les tables BATCH_* si tu utilises Spring Batch
    job:
      enabled: false              # n’exécute pas automatiquement les jobs déclarés

server:
  port: 8080

app:
  payslips:
    storage-dir: ./payslips      # où enregistrer les PDF générés

# Optionnel: pour lancer la génération d’un mois précis
# usage: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Dmonth=2025-09"
